name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/

  train_and_quantize:
    runs-on: ubuntu-latest
    needs: test_suite
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run training and quantization
        run: |
          python src/train.py
          python src/quantize.py

  build_and_test_container:
    runs-on: ubuntu-latest
    needs: train_and_quantize
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t mlops-lr .

      - name: Run Docker Container
        run: docker run mlops-lr
